# By default, look for msgtools autogenerated code in one directory
# above the root directory of the project.  this allows the same
# generated code directory to be shared by multiple repositories 
# that are subdirectories of it (such as a repo for C++ code, another
# for Matlab, another for Python GUI tools, another for a webserver).
MSGTOOLS_CODEGEN_DIR ?= ../obj/CodeGenerator/Cpp/

INCLUDE_DIRS += \
    -I${MSGTOOLS_CODEGEN_DIR} \
    -I$(UCPLATFORM)/msg/


SRC += $(UCPLATFORM)/msg/message_client.cpp \
       $(UCPLATFORM)/msg/message.cpp        \
       $(UCPLATFORM)/msg/message_pool.cpp   \
       $(UCPLATFORM)/msg/message_queue.cpp
